### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by cyouh95** [glennrosenberg/Dasmoto#4]
If you'd like to add some spaces for your navigation bar links, you could specify the `padding` property.

```css
nav a {
  padding: 10px;
  ...
}
```

https://github.com/glennrosenberg/Dasmoto/blob/master/index.html#L14-L16
https://github.com/glennrosenberg/Dasmoto/blob/master/resources/style.css#L39
